export type GameState = 'LESSON_CONCEPT' | 'LESSON_EXAMPLE' | 'CHALLENGE_INPUT' | 'CHALLENGE_SUBMITTED' | 'CHALLENGE_ANIMATION';

export const GameStates: Record<string, GameState> = {
  LESSON_CONCEPT: 'LESSON_CONCEPT',
  LESSON_EXAMPLE: 'LESSON_EXAMPLE',
  CHALLENGE_INPUT: 'CHALLENGE_INPUT',
  CHALLENGE_SUBMITTED: 'CHALLENGE_SUBMITTED',
  CHALLENGE_ANIMATION: 'CHALLENGE_ANIMATION',
};
